MVChost/Controllers/DataTableController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class DataTableController : Controller
    {
        // GET: DataTable
        public ActionResult DataTable()
        {
            var client = new HttpClient();

            int sEcho = int.Parse(Request.Form["sEcho"]);
            int iDisplayStart = int.Parse(Request.Form["iDisplayStart"]);
            int iDisplayLength = int.Parse(Request.Form["iDisplayLength"]);
            int iSortingCols = int.Parse(Request.Form["iSortCol_0"]);
            string sSearch = Request.Form["sSearch"].ToString();
            //string sSearch = Request["parameter1"];;

            // สร้างไฟล์ Json
            var DataJson = JsonConvert.SerializeObject(new
            {
                sEcho = sEcho,
                start = iDisplayStart,
                lenght = iDisplayLength,
                sort = iSortingCols,
                search = sSearch
            });

            var res = client.PostAsJsonAsync("http://localhost:44334/api/DataTable", DataJson).Result;
            var result = res.Content.ReadAsStringAsync().Result;
            return Json(result);
        }
    }
}

MVChost/Controllers/DeleteController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class DeleteController : Controller
    {
        // GET: Delete
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public string deletedata(int Id)
        {
            var client = new HttpClient();
            var result = client.PostAsJsonAsync("http://localhost:44334/api/Delete", JsonConvert.SerializeObject
                (new
                {
                    id = Id
                })).Result;
            return result.Content.ReadAsStringAsync().Result;
        }
    }
}

MVChost/Controllers/EMController/RequestEMController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class RequestEMController : Controller
    {
        // GET: EM
        public ActionResult Testpage(int id=0)
        {
            var client = new HttpClient();
            var request = client.PostAsJsonAsync("http://localhost:44334/api/Request", JsonConvert.SerializeObject
            (new
            {
            id= id
            })).Result;

            if (request.IsSuccessStatusCode)
            {
                var result2 = request.Content.ReadAsStringAsync().Result;
                ViewBag.request = result2;
            }
            else
            {
                ViewBag.error = "CODE_ERROR:003";
            }

            ViewBag.id = id;

            return View();
        }
    }
}

MVChost/Controllers/EMController/SubmitEMController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class SubmitEMController : Controller
    {
        // GET: SubmutEM
        public string submitdata(string Fname, string Lname, string gender, string position, int id = 0)
        {
            var client = new HttpClient();
            var DataJson = JsonConvert.SerializeObject(new
            {
                id = id
            });

          
            var response = client.PostAsJsonAsync("http://localhost:44334/api/Submit", JsonConvert.SerializeObject
            (new
            {
                id = id,
                em_Fname = Fname,
                em_Lname = Lname,
                em_gender = gender,
                em_position = position

            })).Result;

            return "";
        }


    }
}

MVChost/Controllers/EditController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class EditController : Controller
    {
        // GET: Edit
        public string editdata(int id, string Fname, string Lname, string gender, string position)
        {
            var client = new HttpClient();
            var result = client.PostAsJsonAsync("http://localhost:44334/api/Edit", JsonConvert.SerializeObject
            (new
            {
                id = id,
                em_Fname = Fname,
                em_Lname = Lname,
                em_gender = gender,
                em_position = position


            })).Result;
            return result.Content.ReadAsStringAsync().Result;
        }

    }
}

MVChost/Controllers/HomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
            {
            var client = new HttpClient();
            var request = client.PostAsJsonAsync("http://localhost:44334/api/Request", JsonConvert.SerializeObject
            (new
            { })).Result;

            if (request.IsSuccessStatusCode)
            {
                var result2 = request.Content.ReadAsStringAsync().Result;
                ViewBag.request = result2;
            }
            else
            {
                ViewBag.error = "CODE_ERROR:003";
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult EditbyID()
        {
            ViewBag.Massage = "HAHA";
                return View();
        }
        public ActionResult Testpage()
        {
            ViewBag.Massage = "test";
            return View();
        }
    }
}

MVChost/Controllers/RequestController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class RequestController : Controller
    {
        // GET: Request
        public ActionResult request()
        {
            var client = new HttpClient();
            var request = client.PostAsJsonAsync("http://localhost:44334/api/Request", JsonConvert.SerializeObject
            (new
            { })).Result;

            if (request.IsSuccessStatusCode)
            {
                var result2 = request.Content.ReadAsStringAsync().Result;
                ViewBag.request = result2;
            }
            else
            {
                ViewBag.error = "CODE_ERROR:003";
            }


            return View();
    }
}
}

MVChost/Controllers/SubmitController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVChost.Controllers
{
    public class SubmitController : Controller
    {
        // GET: Submit
        public string submitdata(string Fname, string Lname, string gender, string position)
        {
            var client = new HttpClient();
            var response = client.PostAsJsonAsync("http://localhost:44334/api/Submit", JsonConvert.SerializeObject
            (new
            {
                em_Fname = Fname,
                em_Lname = Lname,
                em_gender = gender,
                em_position = position

            })).Result;
            return response.Content.ReadAsStringAsync().Result;
        }
    }
}

MVChost/Views/Edit/EditbyID.cshtml
@{
    ViewBag.Title = "EditbyID";
}

<h2>EditbyID</h2>
<div class="modal-body">
    <p>sdfsdfsdfsdfsfsdfsdfsdf;lkiuyriurgm,f</p>
</div>

MVChost/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVChost/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVChost/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    var text = ViewBag.request;
    //Newtonsoft.Json.Linq.JObject jResult = Newtonsoft.Json.Linq.JObject.Parse(text.ToString());
    //Newtonsoft.Json.Linq.JArray jUser = Newtonsoft.Json.Linq.JArray.Parse(jResult["user"].ToString());
}

@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>*@

<div class="container">
    <div class="row ">

        <div class="searchPage">
            <div class="col-md-2">
                <h3>Name test</h3>
                <input id="Fname" data-param="Fname" class="text searchPage" />
            </div>
            <div class="col-md-2">
                <h3> Last name </h3>
                <input id="Lname" class="searchPage" data-param="Lname" />
            </div>
            <div class="col-md-1">
                <h3>Gender</h3>
                <select name="cars" id="gender" wight="100" class="searchPage" data-param="gender">
                    <option value=""></option>
                    <option value="M">Male</option>
                    <option value="F">Female</option>

                </select>
            </div>
            <div class="col-md-2">
                <h3>
                    Position
                </h3>
                <input id="position" class="searchPage" data-param="position"/>
            </div>
            <div>


            </div>
        </div>
    </div>
    <div class="row">
        <div class="text-center">
            <br />
            @*<button id="bt-submit">Submit</button>*@
            <input type="image" name="go" id="bt-search" src="https://gbf.wiki/images/2/2f/Stamp12.png" width="100" height="100" border-radius="50%">
      
        </div>

    </div>
    <div>
        <br />
        <table id="table"
               class="table table-bordered table-hover table-condensed table-striped"
               style="width:100%">
            <thead>
                <tr>
                    <th> ID</th>
                    <th> Fisrtname</th>
                    <th> Lastname</th>
                    <th> Gender </th>
                    <th> Position</th>
                    <th> Ed it / Delete </th>

                </tr>
            </thead>
        </table>
    </div>
    @*Model
    <div class=" modal fade" id="myModal1" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal">
                        &times;
                    </button>
                    <h4><span></span>Edit</h4>
                </div>
                <div class="modal-body">
                    <form role="form">
                        <div class="form-group">
                            <h3>ID:</h3>
                            <input type="text" disabled="disabled"
                                   class="form-control"
                                   id="id" name="id">
                            <h3>Fisrtname :</h3>
                            <input type="text" class="form-control" id="fname1" name="fname1">
                            <h3>Fisrtname :</h3>
                            <input type="text" class="form-control" id="lname1" name="lname1">
                            <h3>Gender :</h3>
                            <input type="text" class="form-control" id="gender1" name="gender1">
                            <h3>Position :</h3>
                            <input type="text" class="form-control" id="position1" name="position1">
                        </div>
                        <br />
                    </form>
                </div>
                <div class="modal-footer">
                    <div>
                        @Html.ActionLink("Edit", "Testpage", "Home")
                    </div>

                    <button type="button" class="btn btn-success btn-default pull-left" data-dismiss="modal" id="btn_submitedit" name="btn_submitedit"><span></span> Save </button>
                    <button type="button" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                </div>
            </div>
        </div>
    </div>*@
    <div class="text-center">
        <img class="rounded" src="https://gbf.wiki/images/f/f3/Stamp218.png" width="100" height="100" />
        <img class="rounded" src="https://gbf.wiki/images/a/ad/Stamp270.png" width="100" height="100" />
        <img class="rounded" src="https://gbf.wiki/images/5/50/Stamp208.png" width="100" height="100" />
        <img class="rounded" src="https://gbf.wiki/images/0/0e/Stamp88.png" width="100" height="100" />


    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Content/datatables/datatables.all.min.js"></script>
<script type="text/javascript"></script>

<script>
    //$('#bt-submit').on('click', function () {

    //    var Fname = $('#Fname').val();
    //    console.log(Fname);

    //})
    $('#bt-search').on('click', () => {
        var addition = "?search=1";
        $('.searchPage').each(function (i, e) {
            if ($(this).val()) {
                if ($(this).hasClass("datepicker")) // datepicker
                {
                    //addition += "&" + $(this).data().param + "=" + $.datepicker.formatDate('dd M yy', $(this).datepicker('getDate'));

                    addition += "&" + $(this).data().param + "=" + $(this).val();
                }
                else {
                    addition += "&" + $(this).data().param + "=" + $(this).val();
                }
                console.log(addition);
            }
        });

        var thisUrlPage = window.location.href.split("?")[0];
        if (addition != "?search=1") {
            window.location.href = thisUrlPage + (addition);
        }
        else {
            window.location.href = thisUrlPage;
        }
    });
    $('[name=search_clear]').on('click', function (e) {
        e.preventDefault();
        App.blockUI();
        var thisUrlPage = window.location.href.split("?")[0];
        window.location.href = thisUrlPage;
    });
    

    $('#bt-submit').on('click', () => {
       $.ajax({
                url: "@Url.Action("submitdata", "Submit")",
                 data: ({
                    Fname: $("#Fname").val(),
                    Lname: $("#Lname").val(),
                    gender: $("#gender").val(),
                    Position: $("#position").val()
                }),
               success: function (result) {
               console.log(result);
               alert(result);
               table.ajax.reload();
               window.location.reload(true);
               }
       });

        $(document).ready(function () {
            //$("").on("keyup", function () {
            //    var value = $(this).val().toLowerCase();
            $("#table").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });

    })
    $(document).ready(function () {
        $("#btn_delete").click(function () {
            $("#myModal1").modal();
            });
        });

         $(document).ready(function () {
        $("#btn_edit").click(function () {
            $("#myModal1").modal();
            });
         });

          $('#btn_submitedit').on('click', function () {
            $.ajax({
             url: "@Url.Action("editdata", "Edit")", //ControllerName,ActionName
             method: "POST",
            dataType: 'json',
            contentType: "application/json",
            data: JSON.stringify({
                id: global_id,
                Fname: $("#fname1").val(),
                Lname: $("#lname1").val(),
                Gender: $("#gender1").val(),
                Position: $("#position1").val()
           }),
            success: function (result) {
            console.log(result);
            alert(result);
            table.ajax.reload();
            window.location.reload(true);
             }
         });
    });
     //set dataTable
    //var global_id, array_id = new Array();
    //global_id = 0;
    //var gID = 0;
    var table = $('#table').DataTable({
        "sSearch": "sSearch",
        //"searching": false,
            columns: [
                {
                    data: 'id',
                    className: 'text-center'
                },
                {
                    data: 'em_Fname',

                    className: 'text-center'
                },
                {
                    data: 'em_Lname',
                    className: 'text-center'
                },
                {
                    data: 'em_gender',
                    className: 'text-center'
                },
                {
                    data: 'em_position',
                    className: 'text-center'
                },
                {
                    data: function (data) {
                        return '<button class="btn btn-warning" id="btn_edit" name="btn_edit" data-id="' + data["id"] + '">Edit</button> <button class="btn btn-danger" id="btn_delete" name="btn_delete" data-id="id=' + data["id"] + '">Delete</button>'
                    },
                    className: 'text-center'
                },
            ],


            bServerSide: true,
            sAjaxSource: '@Url.Action("DataTable", "DataTable")',
            fnServerData: function (sSource, aoData, fnCallback, oSettings) {
                oSettings.jqXHR = $.ajax({
                    dataType: 'json',
                    type: "POST",
                    url: sSource,
                    data: aoData,
                    success: function (response) {
                        response = JSON.parse(response);
                        fnCallback(response);
                    }
                });
            },
            createdRow: function (row, data) {
                $(row).on("click", "[name=btn_edit]", function () {
                    global_id = data["id"];

                    //$('#id').val(data["id"]);
                    //$('[name=fname1]').val(data["em_Fname"]);
                    //$('[name=lname1]').val(data["em_Lname"]);
                    //$('[name=gender1]').val(data["em_gender"]);
                    //$('[name=position1]').val(data["em_position"]);
                    //$("#myModal1").modal();
                    window.location.href = '@Url.Action("Testpage","RequestEM")?id=' + global_id;
                });

                $(row).on("click", "[name = btn_delete]", function () {
                    console.log("test")
                    global_id = data["id"];
                    console.log(data["id"])
                    $.ajax({
                        url: "@Url.Action("deletedata", "Delete")",
                        method: "POST",
                        dataType: "json",
                        contentType: "application/json",
                        data: JSON.stringify({
                            id: globle_id,
                        }),
                        success: function (result) {
                            console.log(result);
                            alert(result);
                            table.ajax.reload();
                        }
                    });
                });
            },
        });
</script>

MVChost/Views/Home/Testpage.cshtml
@{
    ViewBag.Title = "Testpage";
}

<h2>Testpage</h2>
<div class="form-group">
    <!--<h3>ID:</h3>
    <input type="text" disabled="disabled"-->
           @*class="form-control"*@
           <!--id="id" name="id">-->
    <h3>Fisrtname :</h3>
    <input type="text" class="form-control" id="Fname" name="fname1">
    <h3>Fisrtname :</h3>
    <input type="text" class="form-control" id="Lname" name="lname1">
    <h3>Gender :</h3>
    <input type="text" class="form-control" id="gender" name="gender1">
    <h3>Position :</h3>
    <input type="text" class="form-control" id="position" name="position1">
    <div>
        <button id="bt-submit">submit</button>
    </div>
   
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    @*$('#btn_submitedit').on('click', function () {
            $.ajax({
             url: "@Url.Action("editdata", "Edit")", //ControllerName,ActionName
             method: "POST",
            dataType: 'json',
            contentType: "application/json",
            data: JSON.stringify({
                id: global_id,
                Fname: $("#fname1").val(),
                Lname: $("#lname1").val(),
                Gender: $("#gender1").val(),
                Position: $("#position1").val()
           }),*@

    $('#bt-submit').on('click', () => {
        $.ajax({
            url: "@Url.Action("SubmitEM", "submitdata")",
            data: ({
                Fname: $("#Fname").val(),
                Lname: $("#Lname").val(),
                gender: $("#gender").val(),
                Position: $("#position").val()
            }),
            success: function (result) {
                console.log(result);
                alert(result);
                window.location.reload(true);

            }
        });
    });

</script>

MVChost/Views/RequestEM/Testpage.cshtml
@{
    ViewBag.Title = "Testpage";
    var id = ViewBag.id;

    Newtonsoft.Json.Linq.JObject jResult = new Newtonsoft.Json.Linq.JObject();
    Newtonsoft.Json.Linq.JObject jUser = new Newtonsoft.Json.Linq.JObject();

    if (id > 0)
    {
        var text = ViewBag.request;
        jResult = Newtonsoft.Json.Linq.JObject.Parse(text.ToString());
        jUser = Newtonsoft.Json.Linq.JObject.Parse(jResult["user"].ToString());
    }
}

<h2>Edit info</h2>
<div class="form-group">
    <!--<h3>ID:</h3>
    <input type="text" disabled="disabled"-->
    @*class="form-control"*@
    <!--id="id" name="id">-->
    <h3>Fisrtname :</h3>

    <input type="text" class="form-control" id="Fname" name="fname1" value="@jUser["em_Fname"]">
    <h3>Fisrtname :</h3>
    <input type="text" class="form-control" id="Lname" name="lname1" value="@jUser["em_Lname"]">
    <h3>Gender :</h3>
    <select name="cars" id="gender" wight="100" class="searchPage" data-param="gender" >
        <option value=""></option>
        <option value="M">Male</option>
        <option value="F">Female</option>

    </select>
    <h3>Position :</h3>
    <input type="text" class="form-control" id="position" name="position1" value="@jUser["em_position"]">
    <div>
        <button id="bt-submit">submit</button>
    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    @*$('#btn_submitedit').on('click', function () {
            $.ajax({
             url: "@Url.Action("editdata", "Edit")", //ControllerName,ActionName
             method: "POST",
            dataType: 'json',
            contentType: "application/json",
            data: JSON.stringify({
                id: global_id,
                Fname: $("#fname1").val(),
                Lname: $("#lname1").val(),
                Gender: $("#gender1").val(),
                Position: $("#position1").val()
           }),*@

    $('#bt-submit').on('click', () => {
        $.ajax({
            url: "@Url.Action("submitdata", "SubmitEM")",
            data: ({
                id: @id,
                Fname: $("#Fname").val(),
                Lname: $("#Lname").val(),
                gender: $("#gender").val(),
                Position: $("#position").val()
            }),
            success: function (result) {
                console.log(result);
                alert(result);
                window.location.reload(true);

            }
        });
    });

</script>

MVChost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Register", "Testpage", "RequestEM")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>